service: myservice
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  get_product_info:
    handler: bin/productinfo
    events:
      - http:
          path: productinfo
          method: post