service: myservice
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1

plugins:
  . serverless-iam-roles-per-function

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  get_product_info:
    handler: bin/productinfo
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb.GetItem
        Resource: "arn.aws.dynamodb:${self:provider.region}:*table/${opt:db_name}"
    events:
      - http:
          path: productinfo
          method: post
          cors: true
  add_product:
    handler: bin/addproduct
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb.PutItem
        Resource: "arn.aws.dynamodb:${self:provider.region}:*table/${opt:db_name}"
    events:
      - http:
          path: addproduct
          method: post
          cors: true
  get_products:
    handler: bin/getproducts
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb.GetItem
        Resource: "arn.aws.dynamodb:${self:provider.region}:*table/${opt:db_name}"
    events:
      - http:
          path: getproducts
          method: get
          cors: true